[[headers]]
name = "Referrer-Policy"
value = "strict-origin-when-cross-origin"

[[headers]]
name = "Cache-Control"
value = "public, max-age=31536000"
on = "^/(assets|img)/.*"

[[headers]]
name = "Cache-Control"
value = "public, max-age=3600"
on = "^/(|.*/)$"

[[headers]]
name = "Content-Security-Policy"
value = "frame-ancestors https://pcarrier.com"

[[forms]]
from = "/contact"
to = "pc@rrier.fr"
then = "https://nothing.pcarrier.com/posts/form2mail/"
